import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import Footer from "./(home)/_components/Footer";
import { ReactQueryClientProvider } from "@/providers/queryClient";
import { Toaster } from 'sonner';

// Setup Inter font
const inter = Inter({ subsets: ["latin"] });

// Metadata for the application
export const metadata: Metadata = {
  title: "Now Digital Easy",
  description: "Generated by create next app",
};

// RootLayout component for the overall app structure
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactQueryClientProvider>
        <Toaster position="top-right" richColors />
          {children}
          <Footer/>
        </ReactQueryClientProvider>
      </body>
    </html>
  );
}
